#!/bin/bash

TBB_DIR=/usr/lib/torbrowser/tbb
DATA_DIR=~/.torbrowser

# make sure profile dir exists
if [ ! -d "$DATA_DIR" ]; then
  # copy TBB data
  echo 'copy TBB data'
  mkdir $DATA_DIR
  cp -r $TBB_DIR/Data/* $DATA_DIR
  chmod 700 $DATA_DIR/Tor

  # modify torrc
  echo 'modify torrc'
  mv $DATA_DIR/Tor/torrc $DATA_DIR/Tor/torrc.bak
  sed "s:./Data:$DATA_DIR:" $DATA_DIR/Tor/torrc.bak > $DATA_DIR/Tor/torrc
  rm $DATA_DIR/Tor/torrc.bak

  # modify vidalia.conf
  echo 'modify vidalia.conf'
  mv $DATA_DIR/Vidalia/vidalia.conf $DATA_DIR/Vidalia/vidalia.conf.bak
  cat $DATA_DIR/Vidalia/vidalia.conf.bak | sed "s:../../Data:$DATA_DIR:" | sed "s:../Data:$DATA_DIR:" > $DATA_DIR/Vidalia/vidalia.conf
  rm $DATA_DIR/Vidalia/vidalia.conf.bak
fi

# start Tor Browser
$TBB_DIR/start-tor-browser

